### PR TITLE
Add Instagram & email to tp-staff-social

### PR DESCRIPTION
**Pull request by mariozig**
I failed to add Instagram to the `tp-staff-social` module.  While I was in the code adding Instagram i noticed that Email was missing so i added that too.

### CODE REVIEW

**Comment by mariozig** [comment]
hey guys, is there anything i can do to help get this PR accepted?

**Comment by lumberman** [comment]
@xdima92x Please test this PR and add to your release on Wed.
Thank you @mariozig. I'm sorry that we missed it somehow. Our heads are doing with next generation of LC.

**Comment by mariozig** [comment]
No worries! If something isn't working correctly let me know and I'll submit a fix ASAP.

**Comment by xdima92x** [comment]
Hi @mariozig :) Thank you) We added this feature in the Live Composer 1.2.1

**Pull request closed without merging**
